// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/sportgroup-hq/api/internal/config"
	"github.com/sportgroup-hq/api/internal/controller/grpcserver"
	"github.com/sportgroup-hq/api/internal/controller/httpserver"
	"github.com/sportgroup-hq/api/internal/repo/postgres"
	"github.com/sportgroup-hq/api/internal/service/event"
	"github.com/sportgroup-hq/api/internal/service/group"
	"github.com/sportgroup-hq/api/internal/service/user"
)

// Injectors from wire.go:

func Up() (*Dependencies, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	configPostgres := getPostgresConfig(configConfig)
	postgresPostgres := postgres.New(configPostgres)
	service := user.New(postgresPostgres)
	groupService := group.New(configConfig, postgresPostgres, postgresPostgres)
	eventService := event.New(configConfig, postgresPostgres, postgresPostgres)
	server := httpserver.New(configConfig, service, groupService, eventService)
	grpcserverServer := grpcserver.New(configConfig, service)
	dependencies := NewDependencies(configConfig, server, grpcserverServer, postgresPostgres)
	return dependencies, nil
}

// wire.go:

func getPostgresConfig(cfg *config.Config) config.Postgres {
	return cfg.Postgres
}
